"""Constants for infrastructure layer."""

# Vision OCR constants
VISION_FAST_PROCESSING_TIME_MS = 150
VISION_ACCURATE_PROCESSING_TIME_MS = 800
VISION_BASE_CONFIDENCE_ACCURATE = 0.95
VISION_BASE_CONFIDENCE_FAST = 0.75
VISION_DEFAULT_X_POSITION = 50
VISION_DEFAULT_Y_POSITION = 50
VISION_DEFAULT_LINE_HEIGHT = 30
VISION_DEFAULT_LINE_WIDTH = 400
VISION_DEFAULT_LINE_HEIGHT_BBOX = 25
VISION_CONFIDENCE_VARIANCE = 0.05

# Structure extraction constants
PARAGRAPH_VERTICAL_GAP_THRESHOLD = 50

# Custom Model OCR constants
CUSTOM_MODEL_MOCK_PROCESSING_TIME_MS = 200
CUSTOM_MODEL_MOCK_CONFIDENCE_HIGH = 0.88
CUSTOM_MODEL_MOCK_CONFIDENCE_MEDIUM = 0.85
CUSTOM_MODEL_MOCK_CONFIDENCE_AVG = 0.865
CUSTOM_MODEL_MOCK_X_POSITION = 50
CUSTOM_MODEL_MOCK_Y_POSITION_LINE1 = 50
CUSTOM_MODEL_MOCK_Y_POSITION_LINE2 = 100
CUSTOM_MODEL_MOCK_LINE_WIDTH = 300
CUSTOM_MODEL_MOCK_LINE_HEIGHT = 30
CUSTOM_MODEL_MOCK_LINE2_WIDTH = 350

# HTTP Image Source constants
HTTP_DEFAULT_TIMEOUT_SECONDS = 30.0
HTTP_EXISTS_CHECK_TIMEOUT_SECONDS = 10

# OCR Config defaults
OCR_DEFAULT_MAX_IMAGE_SIZE_MB = 20

# Path selection heuristics
PATH_SELECTION_MEGAPIXEL_THRESHOLD = 2.0
PATH_SELECTION_TEXT_DENSITY_THRESHOLD = 0.3
PIXELS_PER_MEGAPIXEL = 1_000_000

# PDF rendering (Quartz)
QUARTZ_BITMAP_INFO_PREMULTIPLIED_FIRST_LITTLE_ENDIAN = 1 | 0x2000
QUARTZ_BITS_PER_COMPONENT = 8
QUARTZ_BYTES_PER_ROW_AUTO = 0
QUARTZ_WHITE_FILL = (1.0, 1.0, 1.0, 1.0)
PDF_RENDER_SCALE_DEFAULT = 1.5
PDF_FALLBACK_PAGE_COUNT = 1
OCR_TOP_CANDIDATES_COUNT = 1
OCR_CONFIDENCE_FALLBACK = 0.5
OUTPUT_SEPARATOR_WIDTH = 60

# Image generation (testing scripts)
DEFAULT_TEXT_LENGTH = 10
RANDOM_WORD_COUNT_MIN = 3
RANDOM_WORD_COUNT_MAX = 8
RANDOM_WORD_LENGTH_MIN = 3
RANDOM_WORD_LENGTH_MAX = 8
DEFAULT_IMAGE_PADDING = 20
DEFAULT_LINE_SPACING = 10
MULTILINE_PROBABILITY = 0.5
MULTILINE_COUNT_MIN = 2
MULTILINE_COUNT_MAX = 5
IMAGE_WIDTH_CANDIDATES = (800, 1200)
IMAGE_HEIGHT_CANDIDATES = (200, 300, 400)
FONT_SIZE_CANDIDATES = (24, 32, 48)

SYSTEM_FONT_PATHS = (
    "/System/Library/Fonts/Helvetica.ttc",
    "/System/Library/Fonts/Arial.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/TTF/DejaVuSans.ttf",
    "arial.ttf",
)

BACKGROUND_PALETTE = (
    (255, 255, 255),
    (240, 240, 240),
    (255, 250, 240),
)

TEXT_COLOR_PALETTE = (
    (0, 0, 0),
    (50, 50, 50),
    (100, 100, 100),
)
