"""Constants for infrastructure layer."""

# Vision OCR constants
VISION_FAST_PROCESSING_TIME_MS = 150
VISION_ACCURATE_PROCESSING_TIME_MS = 800
VISION_BASE_CONFIDENCE_ACCURATE = 0.95
VISION_BASE_CONFIDENCE_FAST = 0.75
VISION_DEFAULT_X_POSITION = 50
VISION_DEFAULT_Y_POSITION = 50
VISION_DEFAULT_LINE_HEIGHT = 30
VISION_DEFAULT_LINE_WIDTH = 400
VISION_DEFAULT_LINE_HEIGHT_BBOX = 25
VISION_CONFIDENCE_VARIANCE = 0.05

# Structure extraction constants
PARAGRAPH_VERTICAL_GAP_THRESHOLD = 50

# Custom Model OCR constants
CUSTOM_MODEL_MOCK_PROCESSING_TIME_MS = 200
CUSTOM_MODEL_MOCK_CONFIDENCE_HIGH = 0.88
CUSTOM_MODEL_MOCK_CONFIDENCE_MEDIUM = 0.85
CUSTOM_MODEL_MOCK_CONFIDENCE_AVG = 0.865
CUSTOM_MODEL_MOCK_X_POSITION = 50
CUSTOM_MODEL_MOCK_Y_POSITION_LINE1 = 50
CUSTOM_MODEL_MOCK_Y_POSITION_LINE2 = 100
CUSTOM_MODEL_MOCK_LINE_WIDTH = 300
CUSTOM_MODEL_MOCK_LINE_HEIGHT = 30
CUSTOM_MODEL_MOCK_LINE2_WIDTH = 350

# HTTP Image Source constants
HTTP_DEFAULT_TIMEOUT_SECONDS = 30.0
HTTP_EXISTS_CHECK_TIMEOUT_SECONDS = 10

# OCR Config defaults
OCR_DEFAULT_MAX_IMAGE_SIZE_MB = 20
